GET http://localhost:4500/store/Book Store/item
Accept: application/json

###
POST http://localhost:4500/store/Book%20Store/item
Content-Type: application/json

[{  "name": "AWS CDK certification Exam Guide 2021",  "price": 199.99},{  "name": "AWS CDK certification Exam Guide 2021",  "price": 199.99}]
###

###
POST http://localhost:4500/store/add-book
Content-Type: application/json

{
  "name": "Book store ",
  "items": [
    {
      "name": "Spring framework 5",
      "price": 65.99
    },
    {
      "name": "SpringBoot and Microservices",
      "price": 45.99
    },
    {
      "name": "Flask & Python: build RESTful api",
      "price": 39.99
    }
  ]
}


###
POST http://localhost:4500/store
Content-Type: application/json

{
  "name": "Book Store ",
  "items": [
    {
      "name": "Spring framework 5",
      "price": 65.99
    },
    {
      "name": "SpringBoot and Microservices",
      "price": 45.99
    },
    {
      "name": "Flask & Python: build RESTful api",
      "price": 39.99
    }
  ]
}

###
GET http://localhost:4500/store
Accept: application/json


###
GET http://localhost:4500/store/Book store
Accept: application/json


###
GET http://localhost:4500/index
Accept: application/json


POST http://127.0.0.1:3000/item
Accept: application/json

{
  'name':'sugar',
  'price': 1.99
}
